### ISSUE TITLE
Unable to build for webos in version2.7.3

### ISSUE THREAD

**Issue by pedrosilvabos** [interfaced/zombiebox#12]
I  have downloaded from the git and followed the steps in the readme.
I still have a problem when running the server that I have to add "zombiebox-platform-pc": "^2.3.3" to package .json on the dependencies.
after this I can run a localhost web server.
I am unable to build a version to deploy on WebOS, this is the output in the console, could you please help ?

C:\Users\P058279\Desktop\zombieBox\New folder\zombiebox-master>npx zombiebox build webos
Loaded extension about
Loaded extension cutejs
Loaded extension ui
Loaded platform pc
Loaded platform tizen
Loaded platform webos
Error: Failed to parse GCC output: Unexpected token j in JSON at position 434
java.lang.NullPointerException: NAME default$$module$C_$Users$P058279$Desktop$zombieBox$New folder$zombiebox_master$src$application 7 [length: 11] [originalname: Application] [source_file: C:/Users/P058279/Desktop/zombieBox/New folder/
zombiebox-master/.generated/app.js] : ?
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:895)
        at com.google.javascript.jscomp.RemoveUnusedCode.getVarForNameNode(RemoveUnusedCode.java:844)
        at com.google.javascript.jscomp.RemoveUnusedCode.traverseNameNode(RemoveUnusedCode.java:699)
        at com.google.javascript.jscomp.RemoveUnusedCode.traverseNode(RemoveUnusedCode.java:545)
        at com.google.javascript.jscomp.RemoveUnusedCode.traverseChildren(RemoveUnusedCode.java:1247)
        at com.google.javascript.jscomp.RemoveUnusedCode.traverseNode(RemoveUnusedCode.java:554)
        at com.google.javascript.jscomp.RemoveUnusedCode.traverseDeclarationStatement(RemoveUnusedCode.java:1029)
        at com.google.javascript.jscomp.RemoveUnusedCode.traverseNode(RemoveUnusedCode.java:525)
        at com.google.javascript.jscomp.RemoveUnusedCode.traverseChildren(RemoveUnusedCode.java:1247)
        at com.google.javascript.jscomp.RemoveUnusedCode.traverseNode(RemoveUnusedCode.java:554)
        at com.google.javascript.jscomp.RemoveUnusedCode.traverseChildren(RemoveUnusedCode.java:1247)
        at com.google.javascript.jscomp.RemoveUnusedCode.traverseNode(RemoveUnusedCode.java:554)
        at com.google.javascript.jscomp.RemoveUnusedCode.access$1300(RemoveUnusedCode.java:95)
        at com.google.javascript.jscomp.RemoveUnusedCode$Continuation.apply(RemoveUnusedCode.java:1729)
        at com.google.javascript.jscomp.RemoveUnusedCode.traverseAndRemoveUnusedReferences(RemoveUnusedCode.java:387)
        at com.google.javascript.jscomp.RemoveUnusedCode.process(RemoveUnusedCode.java:362)
        at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:317)
        at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:232)
        at com.google.javascript.jscomp.Compiler.performOptimizations(Compiler.java:2434)
        at com.google.javascript.jscomp.Compiler.lambda$stage2Passes$1(Compiler.java:816)
        at com.google.javascript.jscomp.CompilerExecutor$2.call(CompilerExecutor.java:102)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

**Comment by forhitit** [comment]
The application works fine when running
`npx zombiebox run`

After installing MAG npm package
`npm install zombiebox-platform-mag`

The run stopped working. Here is the console message

> Loaded extension about
> Loaded extension cutejs
> Loaded extension dependency-injection
> Loaded extension ui
> Loaded platform lg
> Could not create Application instance, CLI commands that require it will not work: Error: Trying to add not an addon: [object Object] (mag)
